"""empty message

Revision ID: 055463668701
Revises: f8953a8f289b
Create Date: 2024-01-31 15:00:13.644346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '055463668701'
down_revision = 'f8953a8f289b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
